global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['127.0.0.1:5001','127.0.0.1:5000','127.0.0.1:5002','127.0.0.1:5003'] 
